name: Auto Deploy
on:
  push:
    branches: [master]
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: pnpm/action-setup@v2
        with:
          version: 6.24.0
      - name: Install dependencies
        run: pnpm ci
      - name: Build
        run: pnpm run build
      - name: Deploy to GH-Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          GIT_CONFIG_NAME: Outer Wilds Mods Website
          GIT_CONFIG_EMAIL: Outer Wilds Mods Website
          SINGLE_COMMIT: true
